import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import DefaultTemplate from "./_defaultTemplate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultTemplate>{children}</DefaultTemplate>
      </body>
    </html>
  );
}
